### ISSUE TITLE
Error: object ‘odbcConnectAccess’ is not exported by 'namespace:RODBC'

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.db#2]
kwb.db installation fails for **kwb.db@support-64-bit**
see: https://travis-ci.org/KWB-R/kwb.db/jobs/586099918#L7210

**Comment by hsonne** [comment]
Should be fixed now, see 27c72bb. Support of ODBC-calls from 64 bit R now merged into dev, see #1.
