### ISSUE TITLE
Error installing kwb.db

### ISSUE THREAD

**Issue by hsonne** [KWB-R/kwb.db#6]
```
> remotes::install_github("vh-d/odbc32")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo vh-d/odbc32@master
Skipping 1 packages not available: RODBC
√  checking for file 'C:\Users\hsonne\AppData\Local\Temp\RtmpaKU6oc\remotesa407c29421\vh-d-odbc32-1ea1dfe/DESCRIPTION' (599ms)
-  preparing 'odbc32':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'odbc32_0.2.9.9002.tar.gz'
   
Installing package into ‘C:/Users/hsonne/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency 'RODBC' is not available for package 'odbc32'
* removing 'C:/Users/hsonne/Documents/R/win-library/3.6/odbc32'
Fehler: Failed to install 'odbc32' from GitHub:
  (konvertiert von Warnung) installation of package ‘C:/Users/hsonne/AppData/Local/Temp/RtmpaKU6oc/filea404f443379/odbc32_0.2.9.9002.tar.gz’ had non-zero exit status
```

**Comment by hsonne** [comment]
> The link you posted gives you the answer: RODBC depends on R >=4.0.0.

https://community.rstudio.com/t/trouble-installing-package-rodbc/66107/2

**Comment by mrustl** [comment]
so let`s set in DESCRIPTION 

DEPENDS: R (>= 4.0.0) 

for kwb.db ?

**Comment by hsonne** [comment]
I thought about making a branch `r-3.0.0` on https://github.com/hsonne/odbc32 in which the RODBC requirement is "downgraded" to v1.3-16. This version is the latest that depends on R 3.0.0 (https://github.com/cran/RODBC/releases/tag/1.3-16) whereas v1.3-17 already dependes on R 4.0.0.

In kwb.db I will then set 
```
Remotes:
  github::hsonne/odbc32@r-3.0.0
```

**Comment by mrustl** [comment]
Great idea! Hope that works!

**Comment by hsonne** [comment]
Should be solved in new release (on master): https://github.com/KWB-R/kwb.db/releases/tag/v0.5.0
@mrustl Please check and close this issue then.
